dhis2/maps-gl

src/Map.js, src/layers/Boundary.js, src/layers/Choropleth.js, src/layers/ClientCluster.js, src/layers/Dots.js, src/layers/EarthEngine.js, src/layers/Layer.js, src/layers/Markers.js, src/layers/TileLayer.js, src/layers/__tests__/Layer.spec.js
This PR adds support for proportional circles, used to show point facilities in thematic maps. It also includes a fix for hover state, allow a thematic map to have multiple hover layers (one for polygons and one for circles)
=> Proportional circles and hover state

src/__tests__/Map.spec.js
Avoids: TypeError: Super expression must either be null or a function
=> fix: mock mapbox popup compoent

src/Map.css, src/controls/Controls.css, src/controls/Navigation.js, src/controls/controlTypes.js, src/layers/BingLayer.css, src/layers/BingLayer.js
This PR fixes: 
- Bing Maps logo is hidden from map downloads due to CORS issues. We still show the textual source. Added bing maps styles in a separate file.
- Bing Maps logo is also hidden from split view maps (so it's not repeated x times). 
- Extend navigation control to allow the user to reset both rotation and tilting.
=> fix:  hide bing maps logo if download and reset map tilt in navigation control

src/layers/Layer.js, src/layers/LayerGroup.js
Fixes: https://jira.dhis2.org/browse/DHIS2-8496
The tracked entities layer uses "layer group" as it contains both points, lines and polygons. The layer group didn't have the setIndex method, only the individual layers. 
Error shown in the console:
The method is called from the maps app:
https://github.com/dhis2/maps-app/blob/master/src/components/map/Layer.js#L123
This PR adds this method, and calls the same method on each sublayer. 
There are no code changes in Layer.js (only prettifier). 
The PR also includes a fix for the removeFrom(map) method. 
Tracked entities shown above a thematic map:
Tracked entities shown below a thematic map:
=> fix: index and ordering for layer groups (DHIS2-8496)

src/layers/ServerCluster.js
Fixes: https://jira.dhis2.org/browse/DHIS2-8498
When the app or user is quickly zooming the map, the cluster tiles are not yet ready to update. The result is that some clusters remains on the map. The issue is fixed by calling the onMoveEnd method every time a cluster tile is changed. 
Screenshot showing the original issue: 
Screen recording showing that the map is properly updated:
=> fix: trigger cluster update when new cluster tiles are loaded (DHIS2-8498)

src/Map.js
Fixes: https://jira.dhis2.org/browse/DHIS2-8515
We support hover labels for various layers, and this fix removes the label if the mouse cursor leaves the map canvas. 
Shows how the map label is "stuck" at the map edge before this fix:
=> fix: hide label when mouse cursor leaves the map (DHIS2-8515)

src/controls/Controls.css, src/controls/Fullscreen.js
Fixes: https://jira.dhis2.org/browse/DHIS2-8524
Related PR for Maps app: https://github.com/dhis2/maps-app/pull/522
The default behaviour of the fullscreen control is to open the map container in fullscreen. As we also want to include other elements like map title, it's better to use the 2x parent component. This is the same we already use for plugin/dashboard maps, so it simplifies the code. 
Split view maps (which consists of multiple maps still need to move one level up in the DOM hierarchy). 
The PR also includes a style fix for split view map controls which had a transparent hover style which should be solid. 
Before: 
After:
=> fix: use parent container for fullscreen map (DHIS2-8524)

src/controls/Controls.css, src/controls/Fullscreen.js
Fixes: https://jira.dhis2.org/browse/DHIS2-8702
This small PR fixes an issue when the map is opened in fullscreen in a browser which is already in fullscreen mode. This fix is to run the resize method on the map by overriding the _changeIcon method which is called _after_ the fullscreen mode has changed. 
Before this fix: 
After this fix:
=> fix: resize map when toggling fullscreen view (DHIS2-8702)

src/controls/Measure.js
This PRs adds 3 missing locale strings ("Area", "Hecatres" and "Acres") + some code changes to avoid repeating `this.locale`.
This repo is using the locale system of Mapbox GL JS, as maps-gl is an extension of this library, and we also need translations to work with built in controls. 
There is an i18n linkage defined in the maps app: https://github.com/dhis2/maps-app/blob/master/src/components/map/mapLocale.js
Before this PR:
After this PR:
=> fix: add missing locale strings in measure controls

package.json, src/layers/EarthEngine.js, src/layers/Layer.js, src/utils/eeapi.js, yarn.lock
This PR upgrades the following dependencies: 
- Earth Engine API - to support Google Earth Engine layers (loaded on demand)
- Mapbox GL JS - the main mapping library
- polylabel - used to place labels and symbols
- uuid - used to generate unique ids for each layer
With the upgrade of Earth Engine API we could remove a "hack" we had to get the right tile url. 
https://issuetracker.google.com/issues/149420532
=> fix: dependency upgrades

src/layers/Choropleth.js, src/layers/Layer.js
Partly fixes: https://jira.dhis2.org/browse/DHIS2-8642
This PR allows a color value to be passed in as a layer option for choropleths. If there is no color value present for the feature, the fallback will be to this value. It can be used to define a "no data color". 
It also includes a fix for hover labels: If there is no value present for the template provided, we'll show an empty string and not "undefined".
=> feat: color option for choropleth layers (DHIS2-8642)

src/Map.js, src/controls/Fullscreen.js
This PR adds a toggleScrollZoom method to the map class. It will be used to enable scroll zoom when in fullscreen mode. 
Fixes the maps-gl part for: https://jira.dhis2.org/browse/DHIS2-9426
The scroll zoom toggle is removed from the fullscreen control, and will be toggled from the maps app.
=> feat: scroll zoom toggle

src/utils/eeapi.js
"We are in the process of transitioning to new and improved Earth Engine servers, which may require that you update your client libraries.  If you are using an old Earth Engine client, you will receive an error like "Unexpected HTTP error: Earth Engine servers now require client library v0.1.232, released August 19.  Please update to the latest Python or JavaScript version to avoid a break in service." - The Google Earth Engine team
=> fix: ee api upgrade

src/Map.js
Fixes: https://jira.dhis2.org/browse/DHIS2-10071
As we have created a wrapper around the mapbox-gl map instance, we need to pass on the click event in case the app is listening. We use the click event in the DHIS2 Maps to close the right-click context menu.
=> fix: pass map click event back to app (DHIS2-10071)

package.json, src/Map.js, yarn.lock
Partly fixes: https://jira.dhis2.org/browse/DHIS2-10252
Switch to multitouch for map panning to avoid "scroll trap" on dashboards.
=> fix: multitouch for map panning (DHIS2-10252)

src/Map.css, src/layers/EarthEngine.js, src/layers/Events.js, src/layers/Layer.js, src/layers/__tests__/EarthEngine.spec.js, src/utils/__tests__/geometry.spec.js, src/utils/buffers.js, src/utils/geometry.js, src/utils/style.js
Partly fixes: https://jira.dhis2.org/browse/DHIS2-10549
Related maps-app PR: https://github.com/dhis2/maps-app/pull/1504
This PR use the buffer option for EE layers to create circle polygons for each point feature. All polygon features will then be used for aggregations. Both the circle polygon and a dot for the point feature will be displayed on the map. 
The style for feature hover/highlight was adjusted - thicker lines and black outline for events. 
This PR also includes to small style fixes: 
Outline for close 'x' in popups is removed:
Popup is placed above map controls:
=> feat: circle buffer aggregations for EE layers (DHIS2-10549)

package.json, src/Map.js, src/controls/Fullscreen.js, src/controls/MultiTouch.js, yarn.lock
Partly fixes: https://jira.dhis2.org/browse/DHIS2-10413
The mapbox-gl-multitouch dependency we used has been deprecated by the author (https://www.npmjs.com/package/mapbox-gl-multitouch), so I copied the code into the repo and made some smaller adjustments. 
We use multitouch as an alternative to one finger panning on dashboard maps, to avoid a "page scroll trap". We're no longer enabling multitouch by default - it kan be turned on and off with the new `toggleMultiTouch(isEnabled)` method. This allows us to disable one finger panning for dashboard maps, but enable it in fullscreen mode.
=> feat: improve multitouch handling (DHIS2-10413)

src/layers/EarthEngine.js, src/layers/__tests__/EarthEngine.spec.js
Fixes: https://jira.dhis2.org/browse/DHIS2-10604
This PR will add an extra check and only create vector layers if feature data (org units) are available.
=> fix: only add vector layers if needed (DHIS2-10604)

src/controls/Measure.css
This PR improves the styles in the measurement dialog.
maps-gl is not based on react, so the SVGs are included inline. 
Before:
=> chore: improved styles in measurement dialog

src/layers/EarthEngine.js, src/layers/Layer.js, src/layers/__tests__/EarthEngine.spec.js
This PR will allow org unit features in Earth Engine layers to be filtered. 
There is a new `filter(ids)` method where an array of string ids can be passed. This will update the map layer to only show the boundaries of the filtered features. If ids is `null` or `undefined`, all features will be shown. 
This will be used as a quick way to update map when the EE data table is filtered in https://github.com/dhis2/maps-app/pull/1537/
The PR also includes an extra check that the layer is still on the map before setting feature hover state.
=> feat: allow features in EE layers to be filtered

src/Map.css
This PR fixes an issue where the attribution icon is "jumping" when expanded. 
After this PR:
=> fix: compact attribution style

src/layers/EarthEngine.js, src/layers/Layer.js
This PR avoids an app crash when the opacity is changed before the layers are added to the map. There will be a separate PR in `maps-app` when this PR is merged.
=> fix: don't set opacity before layer is added to map

src/layers/Markers.js, src/utils/opacity.js
Fixes: https://jira.dhis2.org/browse/DHIS2-10734
This PR makes sure that opacity is changed for all layers representing facilities (icon, buffer and label). 
Before this PR:
=> fix: icon label opacity

src/layers/DonutCluster.js
Fixes: https://jira.dhis2.org/browse/DHIS2-10889
This PR fixes an issue where donut clusters are not shown for parts of the map. 
Mapbox GL JS divides the the map surface into tiles, and the fix was to wait for all tiles to "load" before rendering the donut clusters (isSourceLoaded). 
Before:
=> fix: wait until donut cluster source is loaded for all tiles (DHIS2-10889)

package.json, src/Map.css, src/Map.js, src/__tests__/Map.spec.js, src/controls/Controls.css, src/controls/FitBounds.js, src/controls/Fullscreen.js, src/controls/Measure.js, src/controls/Navigation.js, src/controls/Search.css, src/controls/Search.js, src/controls/controlTypes.js, src/index.js, src/layers/BingLayer.css, src/layers/ClientCluster.js, src/layers/DonutCluster.js, src/layers/DonutMarker.js, src/layers/EarthEngine.js, src/layers/Layer.js, src/layers/LayerGroup.js, src/layers/Spider.js, src/ui/Label.css, src/ui/Label.js, src/ui/Popup.js, src/utils/geometry.js, src/utils/spiderifier.css, src/utils/spiderifier.js, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-11406
As Mapbox GL JS v2 is no longer under a BSD-3-Clause license, this PR is switching to MapLibre GL JS, a community led fork derived from mapbox-gl-js prior to their switch to a non-OSS license: https://github.com/maplibre/maplibre-gl-js
Main changes: 
- Switch from mapbox-gl to maplibre-gl 
- Raname class names from "mapboxgl-" to "maplibregl-"
- Include mapboxgl-spiderifier code in repo and not as a dependency. 
The reason mapboxgl-spiderifier code was included directly in the repo is that the dependency requires mapbox-gl to display markers. The code was adapted to use markers from maplibre-gl instead. 
It was made a breaking change as the maps-app (and possibly other apps) uses the "mapboxgl-" class names.
After this PR the map controls …
=> BREAKING CHANGE: switch from Mapbox GL JS to MapLibre GL JS (DHIS2-11406)

package.json, src/Map.css, src/Map.js, src/__tests__/Map.spec.js, src/controls/Controls.css, src/controls/FitBounds.js, src/controls/Fullscreen.js, src/controls/Measure.js, src/controls/Navigation.js, src/controls/Search.css, src/controls/Search.js, src/controls/controlTypes.js, src/index.js, src/layers/BingLayer.css, src/layers/ClientCluster.js, src/layers/DonutCluster.js, src/layers/DonutMarker.js, src/layers/EarthEngine.js, src/layers/Layer.js, src/layers/LayerGroup.js, src/layers/Spider.js, src/ui/Label.css, src/ui/Label.js, src/ui/Popup.js, src/utils/geometry.js, src/utils/spiderifier.css, src/utils/spiderifier.js, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-11406
As Mapbox GL JS v2 is no longer under a BSD-3-Clause license, this PR is switching to MapLibre GL JS, a community led fork derived from mapbox-gl-js prior to their switch to a non-OSS license: https://github.com/maplibre/maplibre-gl-js
Main changes: 
- Switch from mapbox-gl to maplibre-gl 
- Raname class names from "mapboxgl-" to "maplibregl-"
- Include mapboxgl-spiderifier code in repo and not as a dependency. 
The reason mapboxgl-spiderifier code was included directly in the repo is that the dependency requires mapbox-gl to display markers. The code was adapted to use markers from maplibre-gl instead. 
BREAKING CHANGE: It was made a breaking change as the maps-app (and possibly other apps) uses the "mapboxgl-" class names.
After this PR …
=> feat: switch from Mapbox GL JS to MapLibre GL JS (DHIS2-11406)

src/utils/opacity.js
Fixes a bug where it was not possible to change the opacity of image symbols: 
Before:
=> fix: symbol opacity

src/Map.js, src/ui/Popup.js
This PR fixes an issue where it is not possible to open a new popup while another is open. You need to click twice, first to close the popup that is currently open, then to open a new one. 
The problem is that the mapping library is calling the onClose handler of the previous popup when a new popup is created, even though the same popup is reused. The fix is to detach the onClose handler when the popup is created, and then attach it again afterwards. 
After this PR opening popups are much quicker:
=> fix: always open popup with single click

src/layers/ClientCluster.js, src/layers/Cluster.js, src/layers/Events.js, src/layers/ServerCluster.js, src/utils/layers.js, src/utils/style.js
This PR makes it possible to specify stroke and count color for event layers. It will make the events easier to separate and to see on different backgrounds. 
Most of the changes in this PR are linting fixes. 
Before: 
Before: 
Before:
=> fix: event stroke and count color

package.json, src/layers/DonutCluster.js, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-11923
This PR makes sure the donut clusters are updated when the layer data source is changed. Waiting for evt.isSourceLoaded is not reliable, and we keep the listener until the layer is removed. 
The maplibe-gl dependency is upgraded to latest 1.15.x version. 
After this PR all donut cluster are shown when the layer is loaded: 
Before only the single events where displayed before map interaction:
=> fix: update donut clusters on source data (DHIS2-11923)

src/layers/EarthEngine.js
As we only need the EE image scale on the server, await is no longer required after #416
=> chore: remove await that is no longer required

src/Map.js, src/layers/LayerGroup.js, src/layers/VectorStyle.js, src/utils/style.js
Fixes: https://jira.dhis2.org/browse/DHIS2-12212
This PR will add offline support to `maps-gl`. It adds support for WebGL fonts hosted locally, and the app using this lib will not break if there is an error. The error will still be displayed in the console. One error could be failure of loading map tiles from an external source. 
Map created offline with errors on the console due to failure of loading basemap tiles:
The PR also fixes a bug in layerGroup.js where "moveToTop" method is changed to the more flexible "move" method.
=> fix: offline support (DHIS2-12212)

src/Map.js
DHIS2 Maps 2.35 uses an old webpack/babel setup and it was difficult to get optional chaining to work without a bigger upgrade. I suggest that we don't use optional chaining in maps-gl before the apps using it supports it.
=> fix: don't use optional chaining in maps-gl

src/earthengine/ee_worker.js
Fixes in maps-gl: https://jira.dhis2.org/browse/DHIS2-11039
This PR will be merged to the EE web worker refactor PR.
This PR will aggregate values for each image band, in addition to all bands combined. We use bands for age/gender groups for population layer. It means that we aggregate values for each age/gender group in addition to all selected groups combined. 
After this PR we return aggregations for each band/group:
```
{
M_0_mean: 0.5269629912153082, 
M_0_sum: 9606.035231643797,
M_1_mean: 1.9892161725946027,
M_1_sum: 36261.52302124757,
M_5_mean: 2.277558791314017,
M_5_sum: 41517.735317703555,
mean: 4.793737955123928,
sum: 87385.29357059492,
}
```
Before we only return for all bands/groups combined:
```
{
mean: 4.793737955123928,
sum: 87385.29357059492,
}
```
There will be another PR …
=> Aggregate values for each band/age group (DHIS2-11039)

src/layers/EarthEngine.js, src/layers/ServerCluster.js
Fixes: https://jira.dhis2.org/browse/DHIS2-12276
This PR adds a check so earth engine aggregations are only calculated if `preload=true` is passed (when the layer is added from DHIS2 Maps, and not on the dashboard) + org units are passed in the `data` option (as they are used for aggregations). This avoids an uncaught error in the console: "Missing org unit features". 
The PR also includes an additional check if tiles are cached before trying to return them for server cluster layer. I have not been able to reproduce this issue locally. It could be related to the uncaught error above as it was reported when server cluster layer was combined with an EE layer.
=> fix: only preload earth engine aggregations if org units are passed (DHIS2-12276)

src/earthengine/ee_worker.js, src/earthengine/ee_worker_loader.js
This PR will use shared worker for Earth Engine layers. 
Currently on dashboard, a worker is created for each map with an Earth Engine layer (20.bundle.js): 
With this PR we can check if the same worker is reused - also between dashboards. 
To inspect the shared worker, use: chrome://inspect/#workers
Confirmation that the shared worker operate as before: 
Added a fallback to Web Worker in Safari (Shared Worker not supported): 
Before the fallback was added: 
About Comlink and Shared Worker: https://github.com/GoogleChromeLabs/comlink#sharedworker
=> fix: use shared worker for Earth Engine layers

src/layers/EarthEngine.js, src/utils/__tests__/core.spec.js, src/utils/__tests__/geometry.spec.js, src/utils/core.js, src/utils/earthengine.js
Fixes: https://jira.dhis2.org/browse/DHIS2-12506
This PR includes better null value handling for Earth Engine layers.
Before this layer if you right-click an area with no data: 
When there is a value, it will still show like this:
Related maps app PR to get "no value" translated: https://github.com/dhis2/maps-app/pull/2017
The long-term plan is to move the popup handling to the Maps app.
=> fix: handle ee null values

src/layers/Layer.js, src/layers/VectorStyle.js
Fixes: https://jira.dhis2.org/browse/DHIS2-12583
This PR fixes an issue when maps a added to a dashboard and a filter is changed. The maps are removed and added again, and we have added a check if the map instance is still present before removing layers or source.
=> fix: make sure map is present before removing layers and source (DHIS2-12583)

src/layers/Boundary.js, src/layers/Choropleth.js, src/layers/ClientCluster.js, src/layers/Cluster.js, src/layers/EarthEngine.js, src/layers/Events.js, src/layers/GeoJson.js, src/layers/Layer.js, src/layers/Markers.js, src/layers/ServerCluster.js, src/layers/__tests__/Layer.spec.js
This PR in an internal refactor to support multiple layer options. Before this PR we pass "isInteractive" as a boolean argument if the map layer should be interactive. In https://jira.dhis2.org/browse/DHIS2-11969 we need another layer option. With this PR layer options is an object where we easily can add new options when we need them. This should also make the code easier to understand.
=> chore: allow multiple layer options

src/layers/LayerGroup.js
This PR fixes a remaining issue from the vector style support: when the user is switching from/to a vector style we need to make sure that the layer is properly redrawn. With this PR, the layers within a layer group are only created once, and then they are removed and added to the map every time the user is switching to/from a vector style. 
Before the this PR a layer group (used for TEI layers) will not show when the user is switching to/from a vector style:
After this PR the layer group is properly redrawn:
=> fix: redraw layer group when map style change

src/layers/Layer.js
This PR will make sure the mouseover label is hidden when the user moves the cursor over an area where there is no label assigned. The fix is needed for an upcoming feature: https://jira.dhis2.org/browse/DHIS2-11969
=> fix: hide label on mouse move

src/layers/Cluster.js
Fixes: https://jira.dhis2.org/browse/DHIS2-12583
This PR adds an extra check if the map still exists before removing an event handler to "unspiderify" an event cluster.
=> fix: check if map still exists before collapsing a cluster (DHIS2-12583)

src/utils/earthengine.js
This PR will perform Earth Engine aggregations for catchment areas. 
Partly fixes: https://jira.dhis2.org/browse/DHIS2-11969
Catchment areas can not be combined with point facility buffers, so this issue was solved by excluding points when no buffer is assigned. When facility points are removed, aggregations will be computed for the remaining polygon features. The facility points are still shown as black dots on the map. 
After this PR:
=> feat: earth engine aggregations for catchment areas (DHIS2-11969)

package.json, src/layers/Cluster.js, yarn.lock
Fixes: https://jira.dhis2.org/browse/DHIS2-12196
This PR upgrades maplibre-gl dependency to the latest version. The upgrade includes a fix to a problem where event clusters are not shown on the innermost zoom level: https://github.com/maplibre/maplibre-gl-js/issues/61
After this PR cluster and spiderify will show on innermost zoom level: 
Before this PR the points will just be stacked on top of each other:
=> fix: show event clusters on innermost zoom level (DHIS2-12196)

src/earthengine/ee_worker.js, src/utils/earthengine.js
This PR will fix a timeout issue with EE aggregations when multiple bands (e.g. age groups) are selected. The fix is to use include a "tileScale" option for ee.Image.reduceRegion: 
https://developers.google.com/earth-engine/apidocs/ee-image-reduceregion
https://gis.stackexchange.com/questions/373250/understanding-tilescale-in-earth-engine
If the "tileScale" is not passed to the EE layer it will be set to default 1. 
After this fix we are able to aggregate population data for all age groups within all districts and chiefdoms in Sierra Leone.
=> fix: use tileScale to avoid ee timeout

src/layers/VectorStyle.js
We attempt to translate the error from maplibre into a meaningful message. 
It is up to the app using the library to catch the error and handle it
=> fix: reject promise if setStyle triggers an error

src/layers/VectorStyle.js
This PR will add to methods that were missing for vector style: 
1. `setVisibility(isVisible)` - changes the visibility for all layers in the vector style
2. `isVisible()` - returns the if the layer is visible (true) or not (false) or not defined (undefined)
The id for all layers that can have the visibility changed are kept in `this._visibleLayers`.
=> fix: vector style visibility

src/utils/labels.js
This PR will revert changes to utils/labels.js except adding value to the feature properties. 
Maplibre GL JS support template strings out-of-the-box like:
-  '{name}'
- '{name}\n{value}'
This could be passed in as the "label" option.
=> chore: revert label changes not needed

src/layers/Layer.js, src/utils/images.js
This PR adds support for SVG images as map symbols. 
Fixes: 
https://dhis2.atlassian.net/browse/DHIS2-14440
Partly fixes: 
https://dhis2.atlassian.net/browse/DHIS2-14438
MapLibre GL JS don't support SVG images: https://github.com/mapbox/mapbox-gl-js/issues/5529
We translate the SVG image to a HTML Image element before it's added to the map. 
We need to know the size when the SVG is translated. Currently we only support the size used for symbols in DHIS2 (16x16). This could be expanded later (by passing in with and height together with the SVG URL). 
The PR also includes a fix so the addImages Promise.all will resolve if one image could not be loaded. If there is an issue with one image, we will write it to the console, but still show the others. 
After this PR (the triangle symbol is …
=> feat: support SVG symbols (DHIS2-14440)

src/layers/Layer.js, src/utils/images.js
=> Revert "feat: support SVG symbols (DHIS2-14440)"

src/Map.js
This PR will allow fitBoundsOptions to be passed in with the map.fitBounds method. This might include map content padding which is useful to control for printed maps. 
The options are documented here: https://maplibre.org/maplibre-gl-js-docs/api/map/#map#fitbounds
=> feat: fit bounds options support

src/earthengine/ee_worker.js, src/earthengine/ee_worker_utils.js
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14261
When we aggregate population data to org units on Google Earth Engine, we currently count a pixel (100x100m) if "at least 0.5% of the pixel is in the region". WorldPop recommends us to use the pixel centroid instead, meaning that the pixel will be counted if the centroid is within the region. 
The different methods gives a small difference. For the Badjia chiefdom in Sierra Leone the population is:
- 12091 when at least 0.5% in region is used
- 12086 when centroid in region is used (5 less)
To use centroid we need to call unweighted() on the reducers: 
https://developers.google.com/earth-engine/guides/reducers_reduce_region#pixels-in-the-region
=> fix: use cell centroids in calculations (DHIS2-14261)

src/layers/DonutCluster.js, src/layers/DonutMarker.js, src/utils/layers.js
Fixes: https://dhis2.atlassian.net/browse/DHIS2-14928
This PR makes it possible to toggle visibility for donut clusters:
The PR also contains a change to allow cluster counts to overlap (to make sure all clusters have a number):
Before:
=> fix: toggle visibility for donut cluster (DHIS2-14928)

src/layers/Choropleth.js, src/layers/Layer.js, src/utils/__tests__/labels.spec.js, src/utils/__tests__/layers.spec.js, src/utils/labels.js, src/utils/layers.js, src/utils/style.js
Fixes: https://dhis2.atlassian.net/browse/DHIS2-15793
Our previous behaviour was to first draw the map layer then set the layer opacity. This worked in most cases, but resulted in a small flash for timeline maps as described in [DHIS2-15793](https://dhis2.atlassian.net/browse/DHIS2-15793). 
This PR allows us to pass in opacity for the various MapLibre layer types so it is set before the first map render.
[DHIS2-15793]: https://dhis2.atlassian.net/browse/DHIS2-15793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
If the opacity is not passed in, the fallback opacity of 1 is used, which is the same as MapLibre uses. 
After this PR there the no opacity flashing is no longer present:
=> fix: draw layers with opacity (DHIS2-15793)

src/Map.js, src/layers/BingLayer.js, src/layers/EarthEngine.js, src/layers/ServerCluster.js
This PR will add a "dhis2-map-rendered" to the map container when the map is fully rendered, and remove it if the map is rendering. 
We will use it in DHIS2 Maps to control when the map is ready for download (used in push analytics). 
Related PR: https://github.com/dhis2/maps-app/pull/3072
=> feat: add class when map is rendered

src/utils/layers.js
Changes will result in a smoother line joins and caps:
Line Before: 
Line after: 
Polygon before:
Polygon after
=> fix: use round style for line-join and line-cap

jest.stub.js, src/controls/controlsLocale.js, src/layers/Layer.js
Implement [DHIS2-15799](https://dhis2.atlassian.net/browse/DHIS2-15799)
Linked maps-app PR: https://github.com/dhis2/maps-app/pull/3204
-------------------
Add logic to display "no data" text if `key` is `value` and `value` is missing when hovering a feature in `onMouseMove` event from `Layer` class. 
-------------------
Before:
https://github.com/dhis2/maps-app/assets/10115948/69215cd4-89c3-4d60-b243-ea8afd81f402
After: ("no data" has been changed to "No data")
https://github.com/dhis2/maps-app/assets/10115948/d377e445-8109-462b-ab1b-44e96f1efb55
[DHIS2-15799]: https://dhis2.atlassian.net/browse/DHIS2-15799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: unclear 'show no data'

.github/workflows/copy-to-d2-ci.yml, README.md
Slightly related to: https://dhis2.atlassian.net/browse/DHIS2-17300
Every branch that is not listed as one of the prod branches (from node-publish.yml)
will now have it's build pushed to d2-ci for every pushed commit.
We can then use these builds during development and testing.
Changes to README
*add docs about how to use the build
New gh workflow file
After building the lib, use yarn pack to create the correct structure of the packaged lib.
Then unzip the result and push that to d2-ci, which can then be installed by the consuming apps.
=> chore: add workflow to publish to d2-ci for non-production branches

.github/dependabot.yml, src/layers/BingLayer.css
Dependabot will group together minor and patch dependency upgrades into single PRs. One for regular minor or patch upgrades, and one for security upgrades.
Major upgrades will still come as separate PRs.
=> chore: group together dependency upgrades to reduce PRs

.github/workflows/copy-to-d2-ci.yml, .github/workflows/node-publish.yml, .gitignore, .hooks/commit-msg, .hooks/pre-commit, .husky/pre-commit, package.json, yarn.lock
Some housekeeping:
- update husky so the hooks actually work instead of getting the "husky-run not found" with every commit
- use node 18 in all workflows (node 16 not supported with latest dependencies)
- do not run the copy-to-ci workflow on dependabot PRs - they don't have access to the needed token, and it shouldnt be necessary anyway.
=> chore: update husky and scripts

src/earthengine/ee_worker.js, src/earthengine/ee_worker_utils.js, src/utils/earthengine.js
Depends on: https://github.com/dhis2/maps-app/pull/3288
This PR refactors the the way we do masking of Earth Engine layers:
- Masking is now only applied to tiles generation and not when we do aggregation. We want to include all pixels when calculating the mean. 
- The WorldPop layers are already masked from the source ("constrained"), so we add a new "unmaskAggregation" option to allow it to be unmasked when we do calculations like mean. 
Before this PR only cells with values are used to calculate the mean and it will not represent the full area:
With this change all cells within the area will be included:
=> feat: new unmask aggregation option

src/controls/controlsLocale.js, src/layers/Layer.js, src/utils/__tests__/labels.spec.js, src/utils/labels.js
Implement [DHIS2-18427](https://dhis2.atlassian.net/browse/DHIS2-18427)
Linked maps-app PR: https://github.com/dhis2/maps-app/pull/3408
Linked maps-app v39 PR: https://github.com/dhis2/maps-app/pull/3415
---
- Tooltip to display 0 when the value is 0 instead of 'No data': https://github.com/dhis2/maps-gl/blob/f1bfa61f413449362507ee59c5df5cbd5b7061e9/src/layers/Layer.js#L350
- Labels with name and value or value only display: 'No data' when value is undefined/null: 
_Note: Here nodata label is passed directly from maps-app instead of from Map.locale as the "label layer" source is not created in the Map context._
https://github.com/dhis2/maps-gl/blob/f1bfa61f413449362507ee59c5df5cbd5b7061e9/src/utils/labels.js#L35
---
Before:
After:
[DHIS2-18427]: …
=> fix: update 'No data' handling

.github/workflows/dhis2-verify-pr-title.yml
1. remove deprecated package used in GHA
Ref: https://github.com/dhis2/analytics/pull/1776
---
See: 
https://github.com/c-hive/gha-yarn-cache?tab=readme-ov-file#deprecated
https://github.com/actions/toolkit/blob/main/packages/cache/README.md
=> chore: remove use of deprecated cache package in GHA

src/layers/AzureLayer.js, src/utils/opacity.js
Linked maps-app PR: https://github.com/dhis2/maps-app/pull/3543
Update `setLayersOpacity` to properly get Azure layers whose id pattern is slightly different from other layers.
=> fix: setting opacity of azure layers
